"""Pydantic schemas for request/response validation."""

from app.schemas.common import (
    BaseSchema,
    TimestampSchema,
    HealthResponse,
    ErrorResponse,
    PaginationParams,
    PaginatedResponse,
)
from app.schemas.user_schemas import (
    UserBase,
    UserCreate,
    UserUpdate,
    UserResponse,
    UserInDB,
    PasswordChange,
    UserListResponse,
    UserProfileResponse,
    UserStatsResponse,
    ChangePasswordRequest,
    UserSearchRequest,
    Token,
    TokenPayload,
    TokenData,
)
from app.schemas.auth_schemas import (
    LoginRequest,
    TokenResponse,
    TokenRefreshRequest,
    TokenRefreshResponse,
    EmailVerificationRequest,
    ForgotPasswordRequest,
    ResetPasswordRequest,
    MessageResponse,
    TokenPayload,
)
from app.schemas.user_profile_schemas import (
    UserProfileBase,
    UserProfileCreate,
    UserProfileUpdate,
    UserProfileResponse,
)
from app.schemas.annotation_schemas import (
    AnnotationBase,
    AnnotationCreate,
    AnnotationUpdate,
    AnnotationResponse,
)
from app.schemas.export_job_schemas import (
    ExportJobBase,
    ExportJobCreate,
    ExportJobResponse,
    ExportJobListResponse,
)
from app.schemas.notification_schemas import (
    NotificationBase,
    NotificationCreate,
    NotificationUpdate,
    NotificationResponse,
    NotificationListResponse,
    NotificationMarkAllReadRequest,
)
from app.schemas.cross_ref_schemas import (
    CrossRefBase,
    CrossRefCreate,
    CrossRefUpdate,
    CrossRefResponse,
    CrossRefWithNoteDetails,
    CrossRefListResponse,
    CrossRefSuggestion,
)
from app.schemas.note_schemas import (
    NoteBase,
    NoteCreate,
    NoteUpdate,
    NoteResponse,
    NoteDetailResponse,
    NoteListResponse,
    NoteSearchRequest,
)
from app.schemas.circle_schemas import (
    CircleBase,
    CircleCreate,
    CircleUpdate,
    CircleResponse,
    CircleDetailResponse,
    CircleListResponse,
    CircleMemberBase,
    CircleMemberCreate,
    CircleMemberUpdate,
    CircleMemberResponse,
    CircleMemberListResponse,
    CircleNoteCreate,
    CircleNoteResponse,
)
from app.schemas.reminder_schemas import (
    ReminderBase,
    ReminderCreate,
    ReminderUpdate,
    ReminderResponse,
    ReminderDetailResponse,
    ReminderListResponse,
    ReminderFilterRequest,
)
from app.schemas.background_job_schemas import (
    JobStatus,
    JobType,
    BackgroundJobBase,
    BackgroundJobCreate,
    BackgroundJobUpdate,
    BackgroundJobResponse,
    BackgroundJobListResponse,
    BackgroundJobStatusResponse,
)

__all__ = [
    # Common
    "BaseSchema",
    "TimestampSchema",
    "HealthResponse",
    "ErrorResponse",
    "PaginationParams",
    "PaginatedResponse",
    # User
    "UserBase",
    "UserCreate",
    "UserUpdate",
    "UserResponse",
    "UserInDB",
    "PasswordChange",
    "UserListResponse",
    "UserProfileResponse",
    "UserStatsResponse",
    "ChangePasswordRequest",
    "UserSearchRequest",
    "Token",
    "TokenPayload",
    "TokenData",
    # Auth
    "LoginRequest",
    "TokenResponse",
    "TokenRefreshRequest",
    "TokenRefreshResponse",
    "EmailVerificationRequest",
    "ForgotPasswordRequest",
    "ResetPasswordRequest",
    "MessageResponse",
    "TokenPayload",
    # User Profile
    "UserProfileBase",
    "UserProfileCreate",
    "UserProfileUpdate",
    "UserProfileResponse",
    # Annotation
    "AnnotationBase",
    "AnnotationCreate",
    "AnnotationUpdate",
    "AnnotationResponse",
    # Export Job
    "ExportJobBase",
    "ExportJobCreate",
    "ExportJobResponse",
    "ExportJobListResponse",
    # Notification
    "NotificationBase",
    "NotificationCreate",
    "NotificationUpdate",
    "NotificationResponse",
    "NotificationListResponse",
    "NotificationMarkAllReadRequest",
    # Cross Reference
    "CrossRefBase",
    "CrossRefCreate",
    "CrossRefUpdate",
    "CrossRefResponse",
    "CrossRefWithNoteDetails",
    "CrossRefListResponse",
    "CrossRefSuggestion",
    # Note
    "NoteBase",
    "NoteCreate",
    "NoteUpdate",
    "NoteResponse",
    "NoteDetailResponse",
    "NoteListResponse",
    "NoteSearchRequest",
    # Circle
    "CircleBase",
    "CircleCreate",
    "CircleUpdate",
    "CircleResponse",
    "CircleDetailResponse",
    "CircleListResponse",
    "CircleMemberBase",
    "CircleMemberCreate",
    "CircleMemberUpdate",
    "CircleMemberResponse",
    "CircleMemberListResponse",
    "CircleNoteCreate",
    "CircleNoteResponse",
    # Reminder
    "ReminderBase",
    "ReminderCreate",
    "ReminderUpdate",
    "ReminderResponse",
    "ReminderDetailResponse",
    "ReminderListResponse",
    "ReminderFilterRequest",
    # Background Job
    "JobStatus",
    "JobType",
    "BackgroundJobBase",
    "BackgroundJobCreate",
    "BackgroundJobUpdate",
    "BackgroundJobResponse",
    "BackgroundJobListResponse",
    "BackgroundJobStatusResponse",
]
